### ISSUE TITLE
You should add this repo to meta-knowledge

### ISSUE THREAD

**Issue by eyalev** [aleen42/PersonalWiki#34]
https://github.com/RichardLitt/meta-knowledge

**Comment by aleen42** [comment]
@eyalev just feel free to open a PR for it in the repository, [*meta-knowledge*](https://github.com/RichardLitt/meta-knowledge), and I appreciate for your motivation.

**Comment by eyalev** [comment]
:+1: 
Added
https://github.com/RichardLitt/meta-knowledge/pull/25/files

**Comment by aleen42** [comment]
@eyalev Thank you so much!
